if(EXISTS "/Users/mblsha/src/github/Musashi/build_test/test_exceptions[1]_tests.cmake")
  include("/Users/mblsha/src/github/Musashi/build_test/test_exceptions[1]_tests.cmake")
else()
  add_test(test_exceptions_NOT_BUILT test_exceptions_NOT_BUILT)
endif()
