if(EXISTS "/Users/mblsha/src/github/Musashi/build_test/test_fixture_example[1]_tests.cmake")
  include("/Users/mblsha/src/github/Musashi/build_test/test_fixture_example[1]_tests.cmake")
else()
  add_test(test_fixture_example_NOT_BUILT test_fixture_example_NOT_BUILT)
endif()
