add_test([=[M68kTest.CPUInitialization]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.CPUInitialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.CPUInitialization]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.BasicInstructionExecution]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.BasicInstructionExecution]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.BasicInstructionExecution]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.MoveInstruction]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.MoveInstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.MoveInstruction]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.AddInstruction]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.AddInstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.AddInstruction]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.MemoryOperations]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.MemoryOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.MemoryOperations]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.BranchInstructions]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.BranchInstructions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.BranchInstructions]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.StackOperations]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.StackOperations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.StackOperations]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.SubroutineCalls]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.SubroutineCalls]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.SubroutineCalls]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.ConditionCodes]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.ConditionCodes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.ConditionCodes]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[M68kTest.InterruptHandling]=]  /Users/mblsha/src/github/Musashi/build_test/test_m68k [==[--gtest_filter=M68kTest.InterruptHandling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[M68kTest.InterruptHandling]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_m68k_TESTS M68kTest.CPUInitialization M68kTest.BasicInstructionExecution M68kTest.MoveInstruction M68kTest.AddInstruction M68kTest.MemoryOperations M68kTest.BranchInstructions M68kTest.StackOperations M68kTest.SubroutineCalls M68kTest.ConditionCodes M68kTest.InterruptHandling)
