if(EXISTS "/Users/mblsha/src/github/Musashi/build_test/test_myfunc[1]_tests.cmake")
  include("/Users/mblsha/src/github/Musashi/build_test/test_myfunc[1]_tests.cmake")
else()
  add_test(test_myfunc_NOT_BUILT test_myfunc_NOT_BUILT)
endif()
