add_test([=[MyFuncTest.Initialization]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.Initialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.Initialization]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.MemoryRegions]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.MemoryRegions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.MemoryRegions]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.MemoryCallbacks]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.MemoryCallbacks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.MemoryCallbacks]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.PCHookAddresses]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.PCHookAddresses]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.PCHookAddresses]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.MixedMemoryAccess]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.MixedMemoryAccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.MixedMemoryAccess]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.RegionPriority]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.RegionPriority]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.RegionPriority]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.ClearRegions]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.ClearRegions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.ClearRegions]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MyFuncTest.ExecutionWithRegions]=]  /Users/mblsha/src/github/Musashi/build_test/test_myfunc [==[--gtest_filter=MyFuncTest.ExecutionWithRegions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MyFuncTest.ExecutionWithRegions]=]  PROPERTIES WORKING_DIRECTORY /Users/mblsha/src/github/Musashi/build_test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_myfunc_TESTS MyFuncTest.Initialization MyFuncTest.MemoryRegions MyFuncTest.MemoryCallbacks MyFuncTest.PCHookAddresses MyFuncTest.MixedMemoryAccess MyFuncTest.RegionPriority MyFuncTest.ClearRegions MyFuncTest.ExecutionWithRegions)
