name: Native CI

on:
  push:
    branches: [ main, master, wasm ]
  pull_request:
    branches: [ main, master, wasm ]
  workflow_dispatch:

jobs:
  # Sanitizer build job (Linux only - catches memory issues effectively)
  sanitizer-tests:
    name: Sanitizer Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake with Sanitizers
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TESTS=ON \
          -DENABLE_SANITIZERS=ON
    
    - name: Build with Sanitizers
      run: |
        cd build
        cmake --build . -j$(nproc)
    
    - name: Run tests with Sanitizers
      run: |
        cd build
        ASAN_OPTIONS=detect_leaks=1:check_initialization_order=1 \
        UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 \
        ctest --output-on-failure