name: TypeScript CI

on:
  push:
    branches: [ main, master, wasm ]
  pull_request:
    branches: [ main, master, wasm ]
  workflow_dispatch:

jobs:
  lint-and-types:
    name: Lint & Type-check (no WASM builds)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x with cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps (root + workspaces)
        run: |
          npm ci
          npm ci --workspaces

      - name: Build packages
        run: npm run build

      - name: Lint
        run: npm run lint || npm run lint:check

      - name: Type-check
        run: npm run typecheck