name: WebAssembly CI

on:
  push:
    branches: [ main, master, wasm ]
  pull_request:
    branches: [ main, master, wasm ]
  workflow_dispatch:

jobs:
  # WebAssembly build job using Fish script
  wasm-build:
    name: WebAssembly Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 'latest'
    
    - name: Install Fish shell
      run: |
        sudo apt-get update
        sudo apt-get install -y fish
        
    - name: Build WASM modules with Fish script
      run: |
        chmod +x build.fish
        fish build.fish
        
    - name: Verify WASM outputs
      run: |
        # Check that WebAssembly modules were created
        test -f musashi.out.js
        test -f musashi.out.wasm
        test -f musashi-node.out.js
        test -f musashi-node.out.wasm
        
        # Check file sizes are reasonable
        for wasm_file in musashi.out.wasm musashi-node.out.wasm; do
          wasm_size=$(stat -c%s "$wasm_file")
          if [ "$wasm_size" -lt 100000 ]; then
            echo "ERROR: $wasm_file seems too small: $wasm_size bytes"
            exit 1
          fi
          echo "$wasm_file size: $wasm_size bytes"
        done
        
        # List all generated files
        ls -la *.out.* *.wasm *.map 2>/dev/null || true
        
        # Verify Perfetto functions are exported
        echo "Checking for Perfetto function exports..."
        for func in perfetto_init perfetto_destroy perfetto_enable_flow \
                    perfetto_enable_memory perfetto_enable_instructions \
                    perfetto_export_trace perfetto_is_initialized; do
          if grep -q "_${func}" musashi.out.js; then
            echo "✓ ${func} exported"
          else
            echo "✗ ${func} NOT exported (expected with Perfetto integration)"
          fi
        done
        
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-modules
        path: |
          musashi.out.js
          musashi.out.wasm
          musashi-node.out.js
          musashi-node.out.wasm
        retention-days: 7